name: Run Gosec in services
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  code-scan:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      # Step 1: Checkout the repository source code
      - name: Checkout Source
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20  # Specify your Go version

      # Step 3: Cache Go dependencies
      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: |
          go mod tidy
          go mod download

      # Step 5: Run Gosec Security Scanner
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
